{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter 1st num in range > 200\n",
      "enter last num in range >250\n",
      "number  200  is not prime\n",
      "number  201  is not prime\n",
      "number  202  is not prime\n",
      "number  203  is not prime\n",
      "number  204  is not prime\n",
      "number  205  is not prime\n",
      "number  206  is not prime\n",
      "number  207  is not prime\n",
      "number  208  is not prime\n",
      "number  209  is not prime\n",
      "number  210  is not prime\n",
      "number  211  is not prime\n",
      "number  212  is not prime\n",
      "number  213  is not prime\n",
      "number  214  is not prime\n",
      "number  215  is not prime\n",
      "number  216  is not prime\n",
      "number  217  is not prime\n",
      "number  218  is not prime\n",
      "number  219  is not prime\n",
      "number  220  is not prime\n",
      "number  221  is not prime\n",
      "number  222  is not prime\n",
      "number  223  is not prime\n",
      "number  224  is not prime\n",
      "number  225  is not prime\n",
      "number  226  is not prime\n",
      "number  227  is not prime\n",
      "number  228  is not prime\n",
      "number  229  is not prime\n",
      "number  230  is not prime\n",
      "number  231  is not prime\n",
      "number  232  is not prime\n",
      "number  233  is not prime\n",
      "number  234  is not prime\n",
      "number  235  is not prime\n",
      "number  236  is not prime\n",
      "number  237  is not prime\n",
      "number  238  is not prime\n",
      "number  239  is not prime\n",
      "number  240  is not prime\n",
      "number  241  is not prime\n",
      "number  242  is not prime\n",
      "number  243  is not prime\n",
      "number  244  is not prime\n",
      "number  245  is not prime\n",
      "number  246  is not prime\n",
      "number  247  is not prime\n",
      "number  248  is not prime\n",
      "number  249  is not prime\n"
     ]
    }
   ],
   "source": [
    "first = int(input(\"enter 1st num in range > \"))\n",
    "last = int(input(\"enter last num in range >\"))\n",
    "found_prime = True\n",
    "\n",
    "for number in range (first, last) :\n",
    "    for i in range(2, int((number)/2)+1) :\n",
    "        print(\"number \", number, \" is not prime\")\n",
    "        found_prime = False\n",
    "        break\n",
    "    if found_prime == True :\n",
    "        print(\"number \", number, \" is prime\")\n",
    "        found_prime = True"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "enter 1st num in range > 1\n",
      "enter last num in range >101\n",
      "1  is a prime number\n",
      "2  is a prime number\n",
      "3  is a prime number\n",
      "4  not\n",
      "5  is a prime number\n",
      "6  not\n",
      "7  is a prime number\n",
      "8  not\n",
      "9  not\n",
      "10  not\n",
      "11  is a prime number\n",
      "12  not\n",
      "13  is a prime number\n",
      "14  not\n",
      "15  not\n",
      "16  not\n",
      "17  is a prime number\n",
      "18  not\n",
      "19  is a prime number\n",
      "20  not\n",
      "21  not\n",
      "22  not\n",
      "23  is a prime number\n",
      "24  not\n",
      "25  not\n",
      "26  not\n",
      "27  not\n",
      "28  not\n",
      "29  is a prime number\n",
      "30  not\n",
      "31  is a prime number\n",
      "32  not\n",
      "33  not\n",
      "34  not\n",
      "35  not\n",
      "36  not\n",
      "37  is a prime number\n",
      "38  not\n",
      "39  not\n",
      "40  not\n",
      "41  is a prime number\n",
      "42  not\n",
      "43  is a prime number\n",
      "44  not\n",
      "45  not\n",
      "46  not\n",
      "47  is a prime number\n",
      "48  not\n",
      "49  not\n",
      "50  not\n",
      "51  not\n",
      "52  not\n",
      "53  is a prime number\n",
      "54  not\n",
      "55  not\n",
      "56  not\n",
      "57  not\n",
      "58  not\n",
      "59  is a prime number\n",
      "60  not\n",
      "61  is a prime number\n",
      "62  not\n",
      "63  not\n",
      "64  not\n",
      "65  not\n",
      "66  not\n",
      "67  is a prime number\n",
      "68  not\n",
      "69  not\n",
      "70  not\n",
      "71  is a prime number\n",
      "72  not\n",
      "73  is a prime number\n",
      "74  not\n",
      "75  not\n",
      "76  not\n",
      "77  not\n",
      "78  not\n",
      "79  is a prime number\n",
      "80  not\n",
      "81  not\n",
      "82  not\n",
      "83  is a prime number\n",
      "84  not\n",
      "85  not\n",
      "86  not\n",
      "87  not\n",
      "88  not\n",
      "89  is a prime number\n",
      "90  not\n",
      "91  not\n",
      "92  not\n",
      "93  not\n",
      "94  not\n",
      "95  not\n",
      "96  not\n",
      "97  is a prime number\n",
      "98  not\n",
      "99  not\n",
      "100  not\n"
     ]
    }
   ],
   "source": [
    "first = int(input(\"enter 1st num in range > \"))\n",
    "last = int(input(\"enter last num in range >\"))\n",
    "\n",
    "for i in range (first, last) :\n",
    "    for j in range (2, int(i/2) + 1) :\n",
    "        if i % j == 0 :\n",
    "            print(i, \" not\")\n",
    "            break\n",
    "    else :\n",
    "        print(i, \" is a prime number\")\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "101\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
